docs/unifiedpush/ups_userguide/index.markdown
docs/unifiedpush/ups_userguide/migration.asciidoc
docs/unifiedpush/ups_userguide/server-installation.asciidoc
docs/unifiedpush/ups_userguide/ups-debugging.asciidoc

Done for https://issues.jboss.org/browse/AGPUSH-1139

Adding migration info to the user guide

---

_posts/2015-01-19-aerogear-android-2.0.0.md

@danielpassos @secondsun can you review and merge (to master and production)?

Adding little Android announcement entry

---

docs/planning/index.markdown

Roadmap for 1.1.0 of UPS update, including a listing of milestone releases towards 1.1.0

Adding milestones for 1.1.0 series of UPS

---

push/index.html

@danbev @sebastienblanc can one of you review and merge ?

Adding WebPush and tweaking some of the text

---

sync/index.markdown

@danbev @secondsun please review/merge

Using new android sync repo

---

download/index.html
ios/index.html

@corinnekrych @matzew mind to view?

update push-sdk(swift) download links

---

css/main.css
index.html

We missed Swift mention on your main home page...

add Swift mention on home page

---

download/index.html
ios/index.html

@corinnekrych mind to give it a spin?

update ios links to point to released artifacts

---

docs/unifiedpush/aerogear-push-chrome/chrome-app.asciidoc
docs/unifiedpush/aerogear-push-chrome/google-setup.asciidoc
docs/unifiedpush/aerogear-push-chrome/index.markdown
docs/unifiedpush/aerogear-push-chrome/register-device.asciidoc

Now that https://github.com/aerogear/aerogear-unifiedpush-server/pull/483 has been merged,  this is the updated guide

Update Chrome App guides

---

OAuth2/index.markdown

extracted from this PR:
https://github.com/matzew/aerogear.org/pull/9

Adding Win/Cordova

---

docs/guides/aerogear-android/how-to-build-aerogear-android.asciidoc

We are not supporting apklib anymore

Replace apklib by aar

---

_includes/navigation.html
_includes/sidebar-docs.html
_includes/sidebar-guides.html
docs/planning/index.markdown
docs/specs/index.markdown
getstarted/guides/index.markdown

* Changed `AeroGearCore` to `AeroGearSDK` in headers in Guides and Docs.
* moved Roadmap to own tab in Navigation
Please review:
* http://staging-aerogearsite.rhcloud.com/getstarted/guides/
* http://staging-aerogearsite.rhcloud.com/docs/specs/
* Road Map in Navigation
Resolving:
https://issues.jboss.org/browse/AEROGEAR-1599
https://issues.jboss.org/browse/AEROGEAR-1598

New design improvements

---

docs/unifiedpush/aerogear-push-ios/troubleshooting.asciidoc

@matzew @abstractj mind to review?

added troubleshooting question for self-signed certs

---

_includes/sidebar-demos.html
_includes/sidebar-guides.html
_includes/sidebar-news.html
_layouts/index.html
css/styles.less
js/script.js

@lfryc We need to remove div `submenu` from TOC. I did it on the static ones, can you help me change the dynamic generated TOC also?
Thanks!

AEROGEAR-1663 solves TOC sidebar responsive issues

---

_posts/2015-03-05-aerogear-webpush-alpha1.md

Adding release blog for WebPush Server

Release blog post for AeroGear WebPush.

---

sync/index.markdown

added sync screencast on landing page

sync screencast

---

docs/unifiedpush/ups_userguide/migration.asciidoc
docs/unifiedpush/ups_userguide/server-installation.asciidoc

Updating the guide to, due to new requirements. see https://issues.jboss.org/browse/AGPUSH-1309 ......
@qmx @sebastienblanc please review and merge

Update ups doc

---

docs/unifiedpush/ups_userguide/admin-ui.asciidoc
docs/unifiedpush/ups_userguide/next.asciidoc
docs/unifiedpush/ups_userguide/server-installation.asciidoc

Updated some links.
@danielpassos @lholmquist can you review/merge?

Fixing broken links and references

---

css/styles.less
js/script.js

@lfryc @corinnekrych Can you please review this one?
[AEROGEAR-1674](https://issues.jboss.org/browse/AEROGEAR-1674)
There is a small jump scrolling down, but it doesn't overlap the header going up. I couldn't find a way to make it work perfect both way :(
If the jump is too bad let me know and I'll search for another solution.

*Almost* fixes sidebar bug

---

_posts/2015-03-16-aerogear-ios-2.2.md

@matzew mind to merge when appropriate?

2.2 announcment

---

docs/unifiedpush/ups_userguide/server-installation.asciidoc

@danielpassos can you review / merge ?

AEROGEAR-1677 : fix grant privileges script

---

docs/unifiedpush/client-registration/index.markdown
docs/unifiedpush/push-message-format-dev/index.markdown
docs/unifiedpush/push-message-format-dev/windows-document-format.asciidoc
docs/unifiedpush/push-message-format/index.markdown

- corrected front matters
- linked docs between each other
@edewit @andresgalante guys, could you please review? :football: 
I'm just not sure linking docs between each other is appropriate, wdyt Andres?

corrected and linked UPS Message Format docs

---

getstarted/downloads/index.html
push/index.html

@lfryc mind to do a quick review?

Adding link  WebPush download and linking to it

---

_data/sdk.yml

update lib links for iOS 2.3 release

---

docs/guides/aerogear-android/how-to-build-aerogear-android.asciidoc

@danielpassos @vibe13 :eyes: ?

Adding in Google Repository Requirement. Thanks @avibelli.

---

_posts/2015-05-08-feedhenry-push-templates.md

The link will not work until the blog has been published. Until then have a [look here](http://www.feedhenry.com/?p=5501&preview=true)

template blog news item

---

docs/guides/aerogear-android/how-to-build-aerogear-android.asciidoc

See: [AGDROID-457](https://issues.jboss.org/browse/AGDROID-457)

Update how to build AeroGear Android

---

docs/specs/aerogear-unifiedpush-nodejs-client/AeroGear.Sender.html
docs/specs/aerogear-unifiedpush-nodejs-client/index.html
docs/specs/aerogear-unifiedpush-nodejs-client/unifiedpush-node-sender.js.html

Update unifiedpush node sender docs to 0.8.0 version

---

getstarted/downloads/index.html

Fixing broken link to docs on this page https://aerogear.org/getstarted/downloads/#simplepush

Link fix (SimplePush Java Client - Docs)

---

Gemfile
_plugins/rss_atom_posts.rb

This PR is to fix the encoding bug on Jekyll

Upgrade to Jekyll 3, plus update asciidoctor

---

README.md

@sebastienblanc @kpiwko here we go

updating ruby install notes

---

docs/unifiedpush/GetStartedwithJavaSender.asciidoc

@matzew Could you review ? 
@edewit I added some info about the Windows Builder, could you check if it's correct ?

AGPUSH-1535 :Sender Guide update

---

docs/unifiedpush/aerogear-push-ios/troubleshooting.asciidoc

@corinnekrych added some info for the handshake error

adding info for 'Remote host closed connection during handshake' issue

---

docs/guides/aerogear-android/push.asciidoc
docs/guides/aerogear-android/store.asciidoc

Don't merge this until AGDroid 3.0.0 is in Central.
@matzew Do these updates make sense?  After we have 3.0.0 staged I will add the javadocs.

Updating Push and Store with API changes for AGDroid 3.0.0

---

docs/unifiedpush/ups_userguide/admin-ui.asciidoc

Doc update mentioned in https://github.com/aerogear/aerogear-unifiedpush-server/pull/724

Clarification on developer role

---

push/index.html

FYI, check out for an action (two words, to check out code from a repo), versus checkout for an object (one word, where you pay for items in a supermarket)

Fixed typos in push/index.html

---

docs/unifiedpush/aerogear-push-android/google-setup.asciidoc

@rsmeral @matzew @secondsun implemented all the suggested edits for the google-related setup  section, PTAL.

fixed spelling and markup in google-related setup

---

docs/unifiedpush/aerogear-push-android/google-setup.asciidoc

Need to use + on lines before and after images to 1) get numbering in numbered list to continue and 2)  make images align with numbered list indent

Fixed step numbering to be continuous

---

docs/guides/aerogear-cordova/AerogearCordovaPush.asciidoc

added Xcode 8 information about the .entitlements file

AGCORDOVA-162 added Xcode 8 information

---

docs/guides/AeroGearPullRequests.asciidoc

I'm picky! picky picky picky :D
well, not really.

Fix minor typo

---

_includes/sidebar-docs.html
_includes/sidebar-guides.html
docs/digger/installation.asciidoc
docs/digger/installation/macos-options.asciidoc
docs/digger/installation/macos-prereqs.asciidoc
docs/digger/installation/macos-setup.asciidoc
docs/specs/index.markdown
getstarted/guides/index.markdown

* Prerequisites for the mac node
* Setting up Ansible variables for provisioning the mac node
* Advanced options for macOS node.

AGDIGGER-120 Add in macOS build farm details

---

docs/digger/admin.asciidoc
docs/digger/admin/use-http-proxy.asciidoc
docs/digger/developer.asciidoc
getstarted/guides/index.markdown

ping @aidenkeating @laurafitzgerald for review

 📝 adding docs about setting up http proxy

---

docker/Dockerfile
docker/README.md

I've added a docker file for local development.

Adding dockerfile 

---

docs/digger/installation.asciidoc
docs/digger/installation/connect-to-rhmap.asciidoc
docs/digger/installation/install-android-sdk.asciidoc
docs/digger/installation/install-jenkins.asciidoc
docs/digger/installation/known-issues.asciidoc
docs/digger/installation/macos-prereqs.asciidoc
docs/digger/installation/macos-setup.asciidoc
docs/digger/installation/overview.asciidoc
docs/digger/installation/prerequisites.asciidoc
docs/digger/installation/run-installer.asciidoc
docs/digger/installation/verify-installation.asciidoc

ping @aidenkeating @laurafitzgerald @aliok @odra @matskiv for review

 📝  add installation guide

---

docs/digger/installation.asciidoc
docs/digger/installation/android-sdk-digger.asciidoc
docs/digger/installation/ansible-installs-jenkins.asciidoc
docs/digger/installation/connect-digger-to-rhmap.asciidoc
docs/digger/installation/digger-install-intro.asciidoc
docs/digger/installation/digger-prereqs.asciidoc
docs/digger/installation/known-issues.asciidoc
docs/digger/installation/macos-prereqs.asciidoc
docs/digger/installation/macos-setup.asciidoc
docs/digger/installation/run-digger-installer.asciidoc
docs/digger/installation/verify-installation.asciidoc
docs/digger/suggestions

To create a little bit of consistency (*shields up in case of this backfiring*).
File names changed to make the docs more modular.
macOS vs Mac, macOS wins. 
Wdyt?
@laurafitzgerald @wei-lee @matskiv @finp

RHMAP-16797 Review upstream aerogear-digger install guide, revision 7

---

docs/digger/installation.asciidoc
docs/digger/installation/installer-variables.asciidoc
docs/digger/installation/run-digger-installer.asciidoc

Document digger-installer variables

RHMAP-17280

---

docs/digger/installation.asciidoc
docs/digger/installation/ansible-installs-jenkins.asciidoc
docs/digger/installation/connect-digger-to-rhmap.asciidoc
docs/digger/installation/digger-install-intro.asciidoc
docs/digger/installation/digger-prereqs.asciidoc
docs/digger/installation/install-android-sdk.asciidoc
docs/digger/installation/known-issues.asciidoc
docs/digger/installation/macos-prereqs.asciidoc
docs/digger/installation/macos-setup.asciidoc
docs/digger/installation/rhmap-properties.asciidoc
docs/digger/installation/run-digger-installer.asciidoc
docs/digger/installation/verify-installation.asciidoc
docs/digger/suggestions

implementing comments from older gdoc, i hope that the current repo does not differ much. https://docs.google.com/document/d/11DNIf2pFG6KcXrMwWXlHz3QnzZpcnifcUTQBzWv_Nj8/edit?ts=59706905# 
Please only review, I will merge it afterwards.
29 aug: + comments from https://github.com/aerogear/aerogear.org/pull/659/

WIP: Rhmap 17324

---

docs/digger/installation/digger-install-intro.asciidoc
docs/digger/installation/known-issues.asciidoc
docs/digger/installation/macos-prereqs.asciidoc

ping @odra @matskiv @laurafitzgerald

Macos bootstrap

---

docs/digger/developer/jenkinsfile-create.asciidoc

Add example of how to customise Jenkinsfile

---

docs/unifiedpush/ups_userguide/server-installation.asciidoc
docs/unifiedpush/ups_userguide/server-installation_advanced.asciidoc

Motivation: https://github.com/aerogear/aerogear-unifiedpush-server/pull/938

Bumps MySQL connector version to 5.1.44

---

.gitignore
README.md
_data/modules.yml
_data/post-tag-mapping.yml
_includes/footer.html
_includes/navigation.html
_includes/sidebar-docs.html
_includes/sidebar-downloads.html
_includes/sidebar-news.html
digger/index.html
docs/specs/index.markdown
getstarted/downloads/index.html
getstarted/downloads/snippets/digger-java-client
index.html

JIRA: AGDIGGER-196
Do the things in README.md to verify locally. However, things didn't work with Ruby 2.1.2 for me but they worked with Ruby 2.2.2.
Note the known issues and missing things in AeroGear.org **Digger related things**: https://issues.jboss.org/browse/AGDIGGER-195
Note the known issues and missing things in AeroGear.org **in general**: https://issues.jboss.org/browse/AEROGEAR-1760

AGDIGGER-196 digger initial docs

---

docs/digger/installation/installer-variables.asciidoc

Added `jenkins_private_key_password` in digger docs

jenkins_private_key_password var

---

docs/digger/installation/installer-variables.asciidoc

this variable is from rhmap, should not be here

Rhmap 18406

---

docs/digger/installation/installer-variables.asciidoc

Reverts aerogear/aerogear.org#682
@laurafitzgerald this variable should be here after all...

Revert "Rhmap 18406 remove rhmap variable"

---

docs/digger/installation/installer-variables.asciidoc

https://issues.jboss.org/browse/AGDIGGER-247

added jenkins pub/private key vars to variables

---

docs/digger/developer.asciidoc
docs/digger/developer/jenkinsfile-fastlane.asciidoc

Opening new pr after update of master to replace this [pr](https://github.com/aerogear/aerogear.org/pull/690)

Agdigger 213 3

---

README.md

**JIRA**
https://issues.jboss.org/browse/AGDIGGER-198
@aliok could you review this change.
Adding in the steps which should be followed when making changes to aerogear.org

add steps for pubilcation

---

docs/digger/admin/known-issues.asciidoc
docs/digger/admin/using-http-proxy.asciidoc
docs/digger/installation/digger-install-intro.asciidoc
docs/digger/installation/digger-prereqs.asciidoc
docs/digger/installation/macos-prereqs.asciidoc
docs/digger/installation/run-digger-installer.asciidoc

updated version of this [pr](https://github.com/aerogear/aerogear.org/pull/689) 
@pmacko1 could you review this when you get some time.

lang fixes

---

docs/digger/admin.asciidoc

https://issues.jboss.org/browse/RHMAP-18937
declutter of https://github.com/aerogear/aerogear.org/pull/683

RHMAP-18937 admin.asciidoc modify asciidoc links

---

docs/digger/installation/macos-setup.asciidoc

splinter from https://github.com/aerogear/aerogear.org/pull/683/files 
https://issues.jboss.org/browse/RHMAP-18944

RHMAP-18944 macos-setup review

---

docs/digger/admin/installing-jenkins-plugins.asciidoc

splinter from https://github.com/aerogear/aerogear.org/pull/683/files
https://issues.jboss.org/browse/RHMAP-18945

RHMAP-18945 update installing-jenkins-plugins

---

docs/digger/admin/about-admin-guide.asciidoc

decluttering https://github.com/aerogear/aerogear.org/pull/683
https://issues.jboss.org/browse/RHMAP-17191

RHMAP-17191 update about-admin-guide

---

README.md

I think stuff got updated to ruby 2.2.2, but readme wasn't updated?

update readme for ruby 2.2.2

---

docs/digger/installation/macos-variables.asciidoc

splinter from https://github.com/aerogear/aerogear.org/pull/683/files
https://issues.jboss.org/browse/RHMAP-18826

RHMAP-18826 rename macos-options to macos-variables + update/review

---

docs/digger/installation/macos-prereqs.asciidoc

original pr https://github.com/aerogear/aerogear.org/pull/704/commits
changes in single commit, minor format correction in known-issues removed- to keep it clean

RHMAP-18943 macos-prereqs review

---

docs/digger/installation/run-digger-installer.asciidoc

https://github.com/aerogear/aerogear.org/pull/711 -> original branch with unnecessary merge commit

RHMAP-18949 update run-digger-installer fixed

---

docs/digger/installation.asciidoc

splinter from https://github.com/aerogear/aerogear.org/pull/683/files
https://issues.jboss.org/browse/RHMAP-18330

merge last: RHMAP-18950 update installation.asciidoc

---

docs/digger/installation/digger-prereqs.asciidoc

splinter from https://github.com/aerogear/aerogear.org/pull/683/files
https://issues.jboss.org/browse/RHMAP-18947
there was a branch RHMAP-18947 with these changes, but it was not merged.

RHMAP-18947 update digger-prereqs

---

docs/digger/installation/macos-variables.asciidoc

https://issues.jboss.org/browse/RHMAP-19580

RHMAP-19580 macos-variables review

---

docs/digger/developer/jenkins-build.asciidoc
docs/digger/developer/jenkinsfile-anatomy.asciidoc
docs/digger/developer/jenkinsfile-create.asciidoc
docs/digger/developer/jenkinsfile-overview.asciidoc

https://issues.jboss.org/browse/AEROGEAR-2182
pr opened to enable commenting directly on text

WIP "AEROGEAR-2182 remove rhmap specific info from devel 1"

---

_includes/footer.html
_includes/navigation.html
community/contribution-guide/index.html
community/processes/index.html
css/styles.less
getting-started/creating-mobile-apps/index.html
getting-started/enabling-mobile-services/index.html
getting-started/index.html
getting-started/installation-and-configuration/index.html
getting-started/overview/index.html
sdks/android/index.html
sdks/cordova/index.html
sdks/index.html
sdks/ios/index.html
sdks/xamarin/index.html
services/crc/index.html
services/index.html
services/keycloak/index.html
services/metrics/index.html
services/mobile-ci-cd/index.html
services/push/index.html

Adds new sitemap and top navigation items

Aerogear 2806

---

_includes/jboss-dropup.html
_layouts/base.html
_layouts/home.html
_layouts/index.html
_layouts/landing-page.html
_layouts/news.html
_layouts/post.html
css/styles.less
css/tabzilla.css

AEROGEAR-3294 removing top-nav icons

---

_includes/homepage-header.html

AEROGEAR-3293 removing platform icons

---

_includes/homepage-header.html
css/styles.less

**Description**
- Update header overview paragraph
- Update call to action link

Update header text and call to action link

---

_includes/homepage-header.html
css/styles.less

Embed promotional video on the landing page on the right hand side of the tagline.
Related JIRA Ticket - https://issues.jboss.org/browse/AEROGEAR-3043
**Screenshots**

[AEROGEAR-3043] Embed promotional video on the landing page

---

css/styles.less
getting-started/overview/index.html

Subject to change (links, content)

[WIP] Getting started page

---

_config.yml
_data/people.yml
_posts/2018-06-27-aerogear-mobile-services-announcement.md

WIP.
The post-date will need to be updated to our launch date prior to merging, as "future" posts will not be rendered.

[WIP] AEROGEAR-3038 - site refresh announcement

---

index.html

Card: https://trello.com/c/i5f1EarI/28-final-landing-page-styling-tweaks
@jasonmadigan

Update text style and remove learn more links

---

_includes/footer.html
_includes/navigation.html
_includes/sidebar-services.html
_layouts/sdks.html
css/styles.less
index.html
sdks/index.html

WIP Aerogear 3570 rework sdks matrix

---

getting-started/index.html

@jasonmadigan - new video uploaded and link updated. Is this the only place we are linking to the video at the moment or do we need to change it somewhere else too?

Update to new Video URL

---

_includes/footer.html
_posts/2018-07-04-aerogear-mobile-services-announcement.md

**Changes**
**Why**
All above links were going to dead pages

Fix feed link

---

_data/services.yml

**What**
Fixing a broken link
**Why**
Me no like broken links.
@pmacko1

fix broken link for github repo

---

community/index.html

Add code owner definition/description

Add code owner

---

_includes/footer.html
legal/export.html

Here's what this new page looks like (it's a copy-paste of the Fedora one). You can also see the updated footer line at the bottom, which links to it:

💬 Add export policy

---

getting-started/index.html

Update Getting Started

---

index.html
sdks/index.html

https://issues.jboss.org/browse/AEROGEAR-9232
https://issues.jboss.org/browse/AEROGEAR-9232
https://issues.jboss.org/browse/AEROGEAR-9232
https://issues.jboss.org/browse/AEROGEAR-9232
https://issues.jboss.org/browse/AEROGEAR-9232

AEROGEAR-9232 - removal of links
