- OAuth2/index.markdown
Based on our announcement last week, here is the same table.
Minor note: rendering looks better on github, than on our own hosted Jekyyl site ;-)
> Adding OAuth2 table, based on release blog

- sync/index.markdown
Motivation:
The aerogear-js sync repository link is currently pointing to a branch
instead of master. That branch has now been merged and the link should
now be updated.
> Updated aerogear-js sync repository to point to master.

- sync/index.markdown
The JS demo for sync is actually an Ember.js based demo,  not a node.js based demo
> should be Ember.js based demo

- _posts/2015-02-17-aerogear-sync.md
Since this is an announcement for the alpha1 release, i think we should just put the link to the Node.js version in the "What's Next" section since it is a super WIP
> Add node.js sync server in the Whats next

- _data/people.yml
- _includes/sidebar-community.html
- community/index.html
umbrella issue: https://issues.jboss.org/browse/AEROGEAR-1600
I've prepared the Community page for publishing.
We are still missing some features that I've temporarily removed:
* github activity (https://issues.jboss.org/browse/AEROGEAR-1555)
* list of contributors (https://issues.jboss.org/browse/AEROGEAR-1642)
> prepare Community page for publishing AEROGEAR-1600

- _includes/breadcrumbs.html
- _layouts/news.html
- _layouts/post.html
- _posts/2012-10-24-aerogear-1.0.0.M6-is-out.md
- _posts/2012-12-20-aerogear-1.0.0.M7-is-out.md
- _posts/2013-01-30-aerogear-1.0.0.M8-is-out.md
- _posts/2013-03-04-aerogear-1.0.0.CR1-is-out.md
- _posts/2013-03-28-aerogear-1.0.0-is-out.md
- _posts/2013-08-19-aerogear-1.1.0-is-out.md
- _posts/2013-12-02-aerogear-1.2.0-is-out.md
- _posts/2014-08-27-aerogear-push-1.0.0-is-out.md
- _posts/2014-09-17-aerogear-push-1.0.1-is-out.md
- _posts/2014-11-06-aerogear-push-1.0.2-is-out.md
- _posts/2014-11-11-aerogear-feedhenry-integration.md
- _posts/2014-11-12-aerogear-feedhenry-devoxx-demo.md
- _posts/2014-11-20-aerogear-unified-push-xpaas.md
- _posts/2014-12-03-aerogear-unified-push-alpha1-is-out.md
- _posts/2015-01-19-aerogear-android-2.0.0.md
- _posts/2015-01-23-aerogear-push-sdk.md
- _posts/2015-01-30-aerogear-ios-2.1.md
- _posts/2015-02-05-aerogear-oauth2.md
- css/styles.less
New layout for news posts called `news`. 
It has more information:
- the author's name and avatar
- date of posting
- module name and logo
- platform
- tags
> adds layout for news posts

- _includes/sidebar-docs.html
- js/script.js
https://issues.jboss.org/browse/AEROGEAR-1624
* scrollspy offset: 75
* `scrollToHash` handles anchor navigation completely (as opposed to previous `onhashchange` handling)
* avoids flickering and wrong position caused by odd timing 
* a bit of cleanup (commented things, unnecessary sidebar-docs items)
---
The correct behavior can be verified here: http://staging-aerogearsite.rhcloud.com/docs/unifiedpush/ups_userguide/index/#_running_the_unifiedpush_server_on_openshift
1. After the load, the page should be scrolled at the position of the anchor (Running UPS on OpenShift)
2. on clicking anchors (e.g. in Table of Contents sidebar), the headers that you click on should be always visible as a first element under the Top Navigation Bar
> fixed anchor scrolling / TOC behavior AEROGEAR-1624

- _data/sdk.yml
- ios/index.md
- sync/index.markdown
update links for iOS 2.2 release.
its the same as the [PR#541](https://github.com/aerogear/aerogear.org/pull/541) but opened against "```master```" now instead of "```new-design```"
@corinnekrych mind to review? I will merge afterwards in master/production branches
> update links for iOS 2.2 rel.

- docs/unifiedpush/aerogear-push-windows/guides.asciidoc
- docs/unifiedpush/aerogear-push-windows/index.markdown
Sometimes it's not obvious for newcomers to the platform in which place such functionality is located. I think this sentence fix this.
> Tweak for Windows sentences

- docs/unifiedpush/ups_userguide/index.asciidoc
- docs/unifiedpush/ups_userguide/server-installation_advanced.asciidoc
This PR shows how to run UPS on different server configurations, like
* Adding some content about running UPS in a WF cluster:
* WF standalone(full)ha mode
* WF Managed Domain mode
* Docker:
* our own Docker image
* just using Docker for DBs (handy during development)
> Adding initial content for HA and Docker setup

- docs/guides/aerogear-android/how-to-build-aerogear-android.asciidoc
* _Google Play Services_ now is part of _repositories_ 
* _compatibility-v4_ and _compatibility-v7-appcompat_ are using only in or example apps. Since all of our examples are gradle projects, it's not necessarily anymore
I think the best way is:
* `rm -rf ~/.m2`
* Build [aerogear-android-push](https://github.com/aerogear/aerogear-android-push/)
* Cross finger
> Improve steps to build AGDroid libraries

- docs/digger/developer.asciidoc
- docs/digger/developer/jenkinsfile-anatomy.asciidoc
- docs/digger/developer/jenkinsfile-create.asciidoc
- docs/digger/developer/jenkinsfile-docs.asciidoc
- docs/digger/developer/jenkinsfile-overview.asciidoc
Add a developer guide for the new build farm. This mostly covers
the introduction of Jenkinsfiles into a repo. The basic anatomy
of a Jenkinsfile, the plugins that Digger provides, the params
that RHMAP provides to Digger.
> RHMAP-16546 Add Developer Guide

- docs/digger/developer/jenkinsfile-create.asciidoc
Document using specific versions of platforms.
JIRA: https://issues.jboss.org/browse/AGDIGGER-176
I only added new documentation to AeroGear.org docs. Any other place didn't make sense as Xcode version is documented inline in Digger-Jenkins sample IOS Jenkinsfile and Android things are in template apps.
Here we have documented how to use a specific XCode version already:
https://github.com/aerogear/aerogear.org/blob/a5d6601de30f0d014721056ac666ef318c72dcc4/docs/digger/developer/jenkinsfile-create.asciidoc#building-applications-with-xcode
Android specific things are explained in the PR.
@finp @pmacko1 may I have your quick review too?
> AGDIGGER-176 Document using specific versions of platforms

- css/styles.less
- Increase font size for improved legibility 
- Update font stack to use native fonts. This should increase readability, load time performance, user experience across devices and font rendering.
For iOS and El Capitan and above on Mac this will default to San Francisco. For Android and Fedora it will default to Roboto. 
With paragraph text (before and after):
> Use system font stack

- _includes/footer.html
**What**
Remove the SDK Links from the footer
Centre the text
**Why**
The links don't go anywhere
We have a link in the top nav already for the main SDK table page
**Before**
**After**
> remove sdk links from fotter

- _includes/sidebar-community.html
- community/contributingGuides/Contributing.asciidoc
- community/index.html
Add a section for the community meeting information in the community page. This change is a follow up on discussions from the community meeting.
[Trello Card](https://trello.com/c/9RLyT77G/52-add-the-community-meeting-recordings-to-aerogearorg)
**Screenshot**
> Add community meeting information to the community page

- README.md
- publish-staging.sh
- publish.sh
**What**
Simplify the process of publishing the site.
**Why**
The staging site is public, the main site is updated regularly and it's possible to build and verify changes to the site locally before merging the changes to master so there is no need to have the step of publishing to staging. 
**Proposal**
[Proposal](https://groups.google.com/forum/#!searchin/aerogear/staging%7Csort:date/aerogear/-D3DDxUC-cM/afUF0fXEDwAJ)
> remove reference to staging

- _posts/2018-07-09-conference-talks-mobile-services.md
**What**
Add a news article template for listing call for conferences and conferences confirmed attended by any member of the AeroGear team where Mobile Services is the topic.
**Why**
Following on from a discussion in the AeroGear Community Meeting we decided to take an [action](https://trello.com/c/J4YyUWXb/36-create-a-list-of-conferences-events-where-we-can-go-and-present-aerogear-mobile-services) to list upcoming conferences in one place
@johnfriz
> template news article for conferences

- _data/services.yml
- _includes/footer.html
- index.html
- sdks/index.html
**What**
Remove custom runtime connector from the site
- From SDK Tables
- From Footer
- Refactor some code to use services data
Can do
- Refactor code so that SDK tables can use data which means easier to update the two locations
> Remove runtime connector

- getting-started/index.html
We support native and cross-platform element.
Suggestion from the product was to remove `native` part as it can be misleading.
> Remove native
